version: '3.7'
services:
  db:
    image: postgres:16.3
    container_name: booking_db
    environment:
      POSTGRES_DB: booking_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rus101
    env_file:
      - .env-non-dev
    ports:
      - 5431:5432

  redis:
    image: redis:7
    container_name: booking_redis

  booking:
    build:
      context: .
    container_name: booking_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: sh -c "alembic upgrade head && exec gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    ports:
      - 7777:8000

  celery:
    build:
      context: .
    container_name: booking_celery
    depends_on:
      - redis
    command: celery -A app.tasks.celeryy:celery_app worker -l INFO --pool=solo
